services:
  portfolio:
    image: ghcr.io/jleveneur/portfolio:latest
    container_name: portfolio
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`jleveneur.com`) || Host(`www.jleveneur.com`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"
      - "traefik.http.routers.portfolio.middlewares=secure-headers@file,compress@file"
      - "traefik.http.services.portfolio.loadbalancer.server.port=3000"

    networks:
      - proxy

networks:
  proxy:
    external: true